#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_sJIK0x0x15TN1x1x15_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=15, 
 * lda=15, ldb=15, ldc=0, mu=1, nu=1, ku=15, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.2)
 */
{
   #define Mb M
   #define Nb N
   const float *stM = A + (15*(Mb));
   const float *stN = B + (15*(Nb));
   #define incAk 15
   const int incAm = 0, incAn = -(15*(Mb));
   #define incBk 15
   const int incBm = -15, incBn = 15;
   const int incAk0 = ((incAk) / 15), incBk0 = ((incBk) / 15);
   #define incCm 1
   const int incCn = (ldc) - (Mb);
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0;
   register float m0;
   register float rC0_0;
   do /* N-loop */
   {
      do /* M-loop */
      {
         rA0 = beta;
         rC0_0 = *pC0;
         rC0_0 *= rA0;
/*
 *       Start pipeline
 */
         rA0 = *pA0;
         rB0 = *pB0;
         m0 = rA0 * rB0;
         rA0 = pA0[1];
         rB0 = pB0[1];

/*
 *       Completely unrolled K-loop
 */
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[2];
         rB0 = pB0[2];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[3];
         rB0 = pB0[3];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[4];
         rB0 = pB0[4];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[5];
         rB0 = pB0[5];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[6];
         rB0 = pB0[6];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[7];
         rB0 = pB0[7];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[8];
         rB0 = pB0[8];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[9];
         rB0 = pB0[9];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[10];
         rB0 = pB0[10];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[11];
         rB0 = pB0[11];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[12];
         rB0 = pB0[12];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[13];
         rB0 = pB0[13];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[14];
         rB0 = pB0[14];
/*
 *       Drain pipe on last iteration of K-loop
 */
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rC0_0 += m0;
         pA0 += incAk;
         pB0 += incBk;
         *pC0 = rC0_0;
         pC0 += incCm;
         pA0 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pA0 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
static void ATL_sJIK0x0x15TN2x1x15_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=15, 
 * lda=15, ldb=15, ldc=0, mu=2, nu=1, ku=15, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.2)
 */
{
   const int Mb = (M>>1)<<1;
   #define Nb N
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (15*(Mb));
   const float *stN = B + (15*(Nb));
   #define incAk 15
   const int incAm = 15, incAn = -(15*(Mb));
   #define incBk 15
   const int incBm = -15, incBn = 15;
   const int incAk0 = ((incAk) / 15), incBk0 = ((incBk) / 15);
   #define incCm 2
   const int incCn = (ldc) - (Mb);
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0, rA1;
   register float rB0;
   register float m0;
   register float rC0_0, rC1_0;
   if (pA0 != stM)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rA0 = beta;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC1_0 = pC0[1];
            rC1_0 *= rA0;
/*
 *          Start pipeline
 */
            rA0 = *pA0;
            rB0 = *pB0;
            rA1 = pA0[15];
            m0 = rA0 * rB0;

/*
 *          Completely unrolled K-loop
 */
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rA1 = pA0[16];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rA1 = pA0[17];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rA1 = pA0[18];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rA1 = pA0[19];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rA1 = pA0[20];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rA1 = pA0[21];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rA1 = pA0[22];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rA1 = pA0[23];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rA1 = pA0[24];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rA1 = pA0[25];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rA1 = pA0[26];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rA1 = pA0[27];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[13];
            rB0 = pB0[13];
            rA1 = pA0[28];
            rC1_0 += m0;
            m0 = rA0 * rB0;
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rA0 = pA0[14];
            rB0 = pB0[14];
            rA1 = pA0[29];
            rC1_0 += m0;
            m0 = rA0 * rB0;
/*
 *          Drain pipe on last iteration of K-loop
 */
            rC0_0 += m0;
            m0 = rA1 * rB0;
            rC1_0 += m0;
            pA0 += incAk;
            pB0 += incBk;
            *pC0 = rC0_0;
            pC0[1] = rC1_0;
            pC0 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=M-Mb)
      ATL_sJIK0x0x15TN1x1x15_a1_bX(k, N, 15, alpha, ca + (15*(Mb)), lda, cb, ldb, beta, cc + (Mb), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_sJIK0x0x15TN1x5x15_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=15, 
 * lda=15, ldb=15, ldc=0, mu=1, nu=5, ku=15, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.2)
 */
{
   #define Mb M
   const int Nb = (N/5)*5;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (15*(Mb));
   const float *stN = B + (15*(Nb));
   #define incAk 15
   const int incAm = 0, incAn = -(15*(Mb));
   #define incBk 15
   const int incBm = -15, incBn = 75;
   const int incAk0 = ((incAk) / 15), incBk0 = ((incBk) / 15);
   #define incCm 1
   const int incCn = (((ldc) << 2)+ldc) - (Mb);
   float *pC0=C, *pC1=pC0+(ldc), *pC2=pC1+(ldc), *pC3=pC2+(ldc), *pC4=pC3+(ldc);
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0, rB1, rB2, rB3, rB4;
   register float m0;
   register float rC0_0, rC0_1, rC0_2, rC0_3, rC0_4;
   if (pB0 != stN)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rA0 = beta;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC0_1 = *pC1;
            rC0_1 *= rA0;
            rC0_2 = *pC2;
            rC0_2 *= rA0;
            rC0_3 = *pC3;
            rC0_3 *= rA0;
            rC0_4 = *pC4;
            rC0_4 *= rA0;
/*
 *          Start pipeline
 */
            rA0 = *pA0;
            rB0 = *pB0;
            rB1 = pB0[15];
            m0 = rA0 * rB0;
            rB2 = pB0[30];
            rB3 = pB0[45];

/*
 *          Completely unrolled K-loop
 */
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rB4 = pB0[60];
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rB1 = pB0[16];
            rB2 = pB0[31];
            rB3 = pB0[46];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[61];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rB1 = pB0[17];
            rB2 = pB0[32];
            rB3 = pB0[47];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[62];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rB1 = pB0[18];
            rB2 = pB0[33];
            rB3 = pB0[48];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[63];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rB1 = pB0[19];
            rB2 = pB0[34];
            rB3 = pB0[49];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[64];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rB1 = pB0[20];
            rB2 = pB0[35];
            rB3 = pB0[50];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[65];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rB1 = pB0[21];
            rB2 = pB0[36];
            rB3 = pB0[51];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[66];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rB1 = pB0[22];
            rB2 = pB0[37];
            rB3 = pB0[52];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[67];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rB1 = pB0[23];
            rB2 = pB0[38];
            rB3 = pB0[53];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[68];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rB1 = pB0[24];
            rB2 = pB0[39];
            rB3 = pB0[54];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[69];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rB1 = pB0[25];
            rB2 = pB0[40];
            rB3 = pB0[55];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[70];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rB1 = pB0[26];
            rB2 = pB0[41];
            rB3 = pB0[56];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[71];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rB1 = pB0[27];
            rB2 = pB0[42];
            rB3 = pB0[57];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[72];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[13];
            rB0 = pB0[13];
            rB1 = pB0[28];
            rB2 = pB0[43];
            rB3 = pB0[58];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[73];
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rA0 = pA0[14];
            rB0 = pB0[14];
            rB1 = pB0[29];
            rB2 = pB0[44];
            rB3 = pB0[59];
            rC0_4 += m0;
            m0 = rA0 * rB0;
            rB4 = pB0[74];
/*
 *          Drain pipe on last iteration of K-loop
 */
            rC0_0 += m0;
            m0 = rA0 * rB1;
            rC0_1 += m0;
            m0 = rA0 * rB2;
            rC0_2 += m0;
            m0 = rA0 * rB3;
            rC0_3 += m0;
            m0 = rA0 * rB4;
            rC0_4 += m0;
            pA0 += incAk;
            pB0 += incBk;
            *pC0 = rC0_0;
            *pC1 = rC0_1;
            *pC2 = rC0_2;
            *pC3 = rC0_3;
            *pC4 = rC0_4;
            pC0 += incCm;
            pC1 += incCm;
            pC2 += incCm;
            pC3 += incCm;
            pC4 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pC1 += incCn;
         pC2 += incCn;
         pC3 += incCn;
         pC4 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=N-Nb)
      ATL_sJIK0x0x15TN1x1x15_a1_bX(M, k, 15, alpha, ca, lda, cb + (15*(Nb)), ldb, beta, cc + (Nb*ldc), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
void ATL_sJIK0x0x15TN15x15x0_a1_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=15, 
 * lda=15, ldb=15, ldc=0, mu=2, nu=5, ku=15, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.2)
 */
{
   const int Mb = (M>>1)<<1;
   const int Nb = (N/5)*5;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (15*(Mb));
   const float *stN = B + (15*(Nb));
   #define incAk 15
   const int incAm = 15, incAn = -(15*(Mb));
   #define incBk 15
   const int incBm = -15, incBn = 75;
   const int incAk0 = ((incAk) / 15), incBk0 = ((incBk) / 15);
   #define incCm 2
   const int incCn = (((ldc) << 2)+ldc) - (Mb);
   float *pC0=C, *pC1=pC0+(ldc), *pC2=pC1+(ldc), *pC3=pC2+(ldc), *pC4=pC3+(ldc);
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0, rA1;
   register float rB0, rB1, rB2, rB3, rB4;
   register float m0;
   register float rC0_0, rC1_0, rC0_1, rC1_1, rC0_2, rC1_2, rC0_3, rC1_3, rC0_4, rC1_4;
   if (pA0 != stM)
   {
      if (pB0 != stN)
      {
         do /* N-loop */
         {
            do /* M-loop */
            {
               rA0 = beta;
               rC0_0 = *pC0;
               rC0_0 *= rA0;
               rC1_0 = pC0[1];
               rC1_0 *= rA0;
               rC0_1 = *pC1;
               rC0_1 *= rA0;
               rC1_1 = pC1[1];
               rC1_1 *= rA0;
               rC0_2 = *pC2;
               rC0_2 *= rA0;
               rC1_2 = pC2[1];
               rC1_2 *= rA0;
               rC0_3 = *pC3;
               rC0_3 *= rA0;
               rC1_3 = pC3[1];
               rC1_3 *= rA0;
               rC0_4 = *pC4;
               rC0_4 *= rA0;
               rC1_4 = pC4[1];
               rC1_4 *= rA0;
/*
 *             Start pipeline
 */
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = pA0[15];
               m0 = rA0 * rB0;
               rB1 = pB0[15];
               rB2 = pB0[30];

/*
 *             Completely unrolled K-loop
 */
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rB3 = pB0[45];
               rB4 = pB0[60];
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rA1 = pA0[16];
               rB1 = pB0[16];
               rB2 = pB0[31];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[46];
               rB4 = pB0[61];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rA1 = pA0[17];
               rB1 = pB0[17];
               rB2 = pB0[32];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[47];
               rB4 = pB0[62];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rA1 = pA0[18];
               rB1 = pB0[18];
               rB2 = pB0[33];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[48];
               rB4 = pB0[63];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[4];
               rB0 = pB0[4];
               rA1 = pA0[19];
               rB1 = pB0[19];
               rB2 = pB0[34];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[49];
               rB4 = pB0[64];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[5];
               rB0 = pB0[5];
               rA1 = pA0[20];
               rB1 = pB0[20];
               rB2 = pB0[35];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[50];
               rB4 = pB0[65];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[6];
               rB0 = pB0[6];
               rA1 = pA0[21];
               rB1 = pB0[21];
               rB2 = pB0[36];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[51];
               rB4 = pB0[66];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[7];
               rB0 = pB0[7];
               rA1 = pA0[22];
               rB1 = pB0[22];
               rB2 = pB0[37];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[52];
               rB4 = pB0[67];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[8];
               rB0 = pB0[8];
               rA1 = pA0[23];
               rB1 = pB0[23];
               rB2 = pB0[38];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[53];
               rB4 = pB0[68];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[9];
               rB0 = pB0[9];
               rA1 = pA0[24];
               rB1 = pB0[24];
               rB2 = pB0[39];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[54];
               rB4 = pB0[69];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[10];
               rB0 = pB0[10];
               rA1 = pA0[25];
               rB1 = pB0[25];
               rB2 = pB0[40];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[55];
               rB4 = pB0[70];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[11];
               rB0 = pB0[11];
               rA1 = pA0[26];
               rB1 = pB0[26];
               rB2 = pB0[41];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[56];
               rB4 = pB0[71];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[12];
               rB0 = pB0[12];
               rA1 = pA0[27];
               rB1 = pB0[27];
               rB2 = pB0[42];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[57];
               rB4 = pB0[72];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[13];
               rB0 = pB0[13];
               rA1 = pA0[28];
               rB1 = pB0[28];
               rB2 = pB0[43];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[58];
               rB4 = pB0[73];
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rA0 = pA0[14];
               rB0 = pB0[14];
               rA1 = pA0[29];
               rB1 = pB0[29];
               rB2 = pB0[44];
               rC1_4 += m0;
               m0 = rA0 * rB0;
               rB3 = pB0[59];
               rB4 = pB0[74];
/*
 *             Drain pipe on last iteration of K-loop
 */
               rC0_0 += m0;
               m0 = rA1 * rB0;
               rC1_0 += m0;
               m0 = rA0 * rB1;
               rC0_1 += m0;
               m0 = rA1 * rB1;
               rC1_1 += m0;
               m0 = rA0 * rB2;
               rC0_2 += m0;
               m0 = rA1 * rB2;
               rC1_2 += m0;
               m0 = rA0 * rB3;
               rC0_3 += m0;
               m0 = rA1 * rB3;
               rC1_3 += m0;
               m0 = rA0 * rB4;
               rC0_4 += m0;
               m0 = rA1 * rB4;
               rC1_4 += m0;
               pA0 += incAk;
               pB0 += incBk;
               *pC0 = rC0_0;
               pC0[1] = rC1_0;
               *pC1 = rC0_1;
               pC1[1] = rC1_1;
               *pC2 = rC0_2;
               pC2[1] = rC1_2;
               *pC3 = rC0_3;
               pC3[1] = rC1_3;
               *pC4 = rC0_4;
               pC4[1] = rC1_4;
               pC0 += incCm;
               pC1 += incCm;
               pC2 += incCm;
               pC3 += incCm;
               pC4 += incCm;
               pA0 += incAm;
               pB0 += incBm;
            }
            while(pA0 != stM);
            pC0 += incCn;
            pC1 += incCn;
            pC2 += incCn;
            pC3 += incCn;
            pC4 += incCn;
            pA0 += incAn;
            pB0 += incBn;
         }
         while(pB0 != stN);
      }
   }
   if (k=N-Nb)
      ATL_sJIK0x0x15TN2x1x15_a1_bX(M, k, 15, alpha, ca, lda, cb + (15*(Nb)), ldb, beta, cc + (Nb*ldc), ldc);
   if (Nb && (k=M-Mb))
      ATL_sJIK0x0x15TN1x5x15_a1_bX(k, Nb, 15, alpha, ca + (15*(Mb)), lda, cb, ldb, beta, cc + (Mb), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
