#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#include "atlas_prefetch.h"

#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#include "atlas_prefetch.h"

static void ATL_zJIK0x0x34TN1x1x34_a1_bX
   (const int M, const int N, const int K, const double alpha, const double * ATL_RESTRICT A, const int lda, const double * ATL_RESTRICT B, const int ldb, const double beta, double * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=34, 
 * lda=34, ldb=34, ldc=0, mu=1, nu=1, ku=34, pf=1
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.2)
 */
{
   #define Mb M
   #define Nb N
   const double *stM = A + (((Mb) << 5)+((Mb) << 1));
   const double *stN = B + (((Nb) << 5)+((Nb) << 1));
   const double *pfA = stM;
   const int incPFA0 = (((int)(stM - A))*1*1)/(M*N*sizeof(double));
   const int incPFA = (1 > incPFA0) ? 1 : incPFA0;
   #define incAk 34
   const int incAm = 0, incAn = -(((Mb) << 5)+((Mb) << 1));
   #define incBk 34
   const int incBm = -34, incBn = 34;
   const int incAk0 = ((incAk) / 34), incBk0 = ((incBk) / 34);
   #define incCm 2
   const int incCn = (((ldc) << 1)) - (((Mb) << 1));
   double *pC0=C;
   const double *pA0=A;
   const double *pB0=B;
   register int k;
   register double rA0;
   register double rB0;
   register double m0, m1;
   register double rC0_0;
   do /* N-loop */
   {
      do /* M-loop */
      {
         ATL_pfl1R(pfA);
         pfA += incPFA;
         rA0 = beta;
         rC0_0 = *pC0;
         rC0_0 *= rA0;
/*
 *       Start pipeline
 */
         rA0 = *pA0;
         rB0 = *pB0;
         m0 = rA0 * rB0;
         rA0 = pA0[1];
         rB0 = pB0[1];
         m1 = rA0 * rB0;
         rA0 = pA0[2];
         rB0 = pB0[2];

/*
 *       Completely unrolled K-loop
 */
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[3];
         rB0 = pB0[3];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[4];
         rB0 = pB0[4];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[5];
         rB0 = pB0[5];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[6];
         rB0 = pB0[6];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[7];
         rB0 = pB0[7];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[8];
         rB0 = pB0[8];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[9];
         rB0 = pB0[9];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[10];
         rB0 = pB0[10];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[11];
         rB0 = pB0[11];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[12];
         rB0 = pB0[12];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[13];
         rB0 = pB0[13];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[14];
         rB0 = pB0[14];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[15];
         rB0 = pB0[15];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[16];
         rB0 = pB0[16];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[17];
         rB0 = pB0[17];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[18];
         rB0 = pB0[18];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[19];
         rB0 = pB0[19];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[20];
         rB0 = pB0[20];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[21];
         rB0 = pB0[21];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[22];
         rB0 = pB0[22];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[23];
         rB0 = pB0[23];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[24];
         rB0 = pB0[24];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[25];
         rB0 = pB0[25];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[26];
         rB0 = pB0[26];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[27];
         rB0 = pB0[27];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[28];
         rB0 = pB0[28];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[29];
         rB0 = pB0[29];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[30];
         rB0 = pB0[30];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[31];
         rB0 = pB0[31];
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rA0 = pA0[32];
         rB0 = pB0[32];
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rA0 = pA0[33];
         rB0 = pB0[33];
/*
 *       Drain pipe on last iteration of K-loop
 */
         rC0_0 += m1;
         m1 = rA0 * rB0;
         rC0_0 += m0;
         rC0_0 += m1;
         pA0 += incAk;
         pB0 += incBk;
         *pC0 = rC0_0;
         pC0 += incCm;
         pA0 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pA0 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
void ATL_zJIK0x0x34TN34x34x0_a1_bX
   (const int M, const int N, const int K, const double alpha, const double * ATL_RESTRICT A, const int lda, const double * ATL_RESTRICT B, const int ldb, const double beta, double * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=0, KB=34, 
 * lda=34, ldb=34, ldc=0, mu=10, nu=1, ku=34, pf=1
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.2)
 */
{
   const int Mb = (M/10)*10;
   #define Nb N
   const double *ca=A, *cb=B;
   double *cc=C;
   const double *stM = A + (((Mb) << 5)+((Mb) << 1));
   const double *stN = B + (((Nb) << 5)+((Nb) << 1));
   const double *pfA = stM;
   const int incPFA0 = (((int)(stM - A))*10*1)/(M*N*sizeof(double));
   const int incPFA = (1 > incPFA0) ? 1 : incPFA0;
   #define incAk 34
   const int incAm = 306, incAn = -(((Mb) << 5)+((Mb) << 1));
   #define incBk 34
   const int incBm = -34, incBn = 34;
   const int incAk0 = ((incAk) / 34), incBk0 = ((incBk) / 34);
   #define incCm 20
   const int incCn = (((ldc) << 1)) - (((Mb) << 1));
   double *pC0=C;
   const double *pA0=A;
   const double *pB0=B;
   register int k;
   register double rA0, rA1, rA2, rA3, rA4, rA5, rA6, rA7, rA8, rA9;
   register double rB0;
   register double m0, m1, m2, m3, m4;
   register double rC0_0, rC1_0, rC2_0, rC3_0, rC4_0, rC5_0, rC6_0, rC7_0, rC8_0, rC9_0;
   if (pA0 != stM)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            ATL_pfl1R(pfA);
            pfA += incPFA;
            rA0 = beta;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC1_0 = pC0[2];
            rC1_0 *= rA0;
            rC2_0 = pC0[4];
            rC2_0 *= rA0;
            rC3_0 = pC0[6];
            rC3_0 *= rA0;
            rC4_0 = pC0[8];
            rC4_0 *= rA0;
            rC5_0 = pC0[10];
            rC5_0 *= rA0;
            rC6_0 = pC0[12];
            rC6_0 *= rA0;
            rC7_0 = pC0[14];
            rC7_0 *= rA0;
            rC8_0 = pC0[16];
            rC8_0 *= rA0;
            rC9_0 = pC0[18];
            rC9_0 *= rA0;
/*
 *          Start pipeline
 */
            rA0 = *pA0;
            rB0 = *pB0;
            m0 = rA0 * rB0;
            rA1 = pA0[34];
            rA2 = pA0[68];
            m1 = rA1 * rB0;
            rA3 = pA0[102];
            rA4 = pA0[136];
            m2 = rA2 * rB0;
            rA5 = pA0[170];
            rA6 = pA0[204];
            m3 = rA3 * rB0;
            rA7 = pA0[238];
            rA8 = pA0[272];
            m4 = rA4 * rB0;
            rA9 = pA0[306];

/*
 *          Completely unrolled K-loop
 */
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rA1 = pA0[35];
            rA2 = pA0[69];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[103];
            rA4 = pA0[137];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[171];
            rA6 = pA0[205];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[239];
            rA8 = pA0[273];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[307];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rA1 = pA0[36];
            rA2 = pA0[70];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[104];
            rA4 = pA0[138];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[172];
            rA6 = pA0[206];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[240];
            rA8 = pA0[274];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[308];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rA1 = pA0[37];
            rA2 = pA0[71];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[105];
            rA4 = pA0[139];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[173];
            rA6 = pA0[207];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[241];
            rA8 = pA0[275];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[309];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rA1 = pA0[38];
            rA2 = pA0[72];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[106];
            rA4 = pA0[140];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[174];
            rA6 = pA0[208];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[242];
            rA8 = pA0[276];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[310];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rA1 = pA0[39];
            rA2 = pA0[73];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[107];
            rA4 = pA0[141];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[175];
            rA6 = pA0[209];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[243];
            rA8 = pA0[277];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[311];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rA1 = pA0[40];
            rA2 = pA0[74];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[108];
            rA4 = pA0[142];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[176];
            rA6 = pA0[210];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[244];
            rA8 = pA0[278];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[312];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rA1 = pA0[41];
            rA2 = pA0[75];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[109];
            rA4 = pA0[143];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[177];
            rA6 = pA0[211];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[245];
            rA8 = pA0[279];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[313];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rA1 = pA0[42];
            rA2 = pA0[76];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[110];
            rA4 = pA0[144];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[178];
            rA6 = pA0[212];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[246];
            rA8 = pA0[280];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[314];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rA1 = pA0[43];
            rA2 = pA0[77];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[111];
            rA4 = pA0[145];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[179];
            rA6 = pA0[213];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[247];
            rA8 = pA0[281];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[315];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rA1 = pA0[44];
            rA2 = pA0[78];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[112];
            rA4 = pA0[146];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[180];
            rA6 = pA0[214];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[248];
            rA8 = pA0[282];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[316];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rA1 = pA0[45];
            rA2 = pA0[79];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[113];
            rA4 = pA0[147];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[181];
            rA6 = pA0[215];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[249];
            rA8 = pA0[283];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[317];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rA1 = pA0[46];
            rA2 = pA0[80];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[114];
            rA4 = pA0[148];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[182];
            rA6 = pA0[216];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[250];
            rA8 = pA0[284];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[318];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[13];
            rB0 = pB0[13];
            rA1 = pA0[47];
            rA2 = pA0[81];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[115];
            rA4 = pA0[149];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[183];
            rA6 = pA0[217];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[251];
            rA8 = pA0[285];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[319];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[14];
            rB0 = pB0[14];
            rA1 = pA0[48];
            rA2 = pA0[82];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[116];
            rA4 = pA0[150];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[184];
            rA6 = pA0[218];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[252];
            rA8 = pA0[286];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[320];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[15];
            rB0 = pB0[15];
            rA1 = pA0[49];
            rA2 = pA0[83];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[117];
            rA4 = pA0[151];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[185];
            rA6 = pA0[219];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[253];
            rA8 = pA0[287];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[321];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[16];
            rB0 = pB0[16];
            rA1 = pA0[50];
            rA2 = pA0[84];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[118];
            rA4 = pA0[152];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[186];
            rA6 = pA0[220];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[254];
            rA8 = pA0[288];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[322];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[17];
            rB0 = pB0[17];
            rA1 = pA0[51];
            rA2 = pA0[85];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[119];
            rA4 = pA0[153];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[187];
            rA6 = pA0[221];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[255];
            rA8 = pA0[289];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[323];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[18];
            rB0 = pB0[18];
            rA1 = pA0[52];
            rA2 = pA0[86];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[120];
            rA4 = pA0[154];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[188];
            rA6 = pA0[222];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[256];
            rA8 = pA0[290];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[324];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[19];
            rB0 = pB0[19];
            rA1 = pA0[53];
            rA2 = pA0[87];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[121];
            rA4 = pA0[155];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[189];
            rA6 = pA0[223];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[257];
            rA8 = pA0[291];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[325];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[20];
            rB0 = pB0[20];
            rA1 = pA0[54];
            rA2 = pA0[88];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[122];
            rA4 = pA0[156];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[190];
            rA6 = pA0[224];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[258];
            rA8 = pA0[292];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[326];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[21];
            rB0 = pB0[21];
            rA1 = pA0[55];
            rA2 = pA0[89];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[123];
            rA4 = pA0[157];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[191];
            rA6 = pA0[225];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[259];
            rA8 = pA0[293];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[327];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[22];
            rB0 = pB0[22];
            rA1 = pA0[56];
            rA2 = pA0[90];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[124];
            rA4 = pA0[158];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[192];
            rA6 = pA0[226];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[260];
            rA8 = pA0[294];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[328];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[23];
            rB0 = pB0[23];
            rA1 = pA0[57];
            rA2 = pA0[91];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[125];
            rA4 = pA0[159];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[193];
            rA6 = pA0[227];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[261];
            rA8 = pA0[295];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[329];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[24];
            rB0 = pB0[24];
            rA1 = pA0[58];
            rA2 = pA0[92];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[126];
            rA4 = pA0[160];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[194];
            rA6 = pA0[228];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[262];
            rA8 = pA0[296];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[330];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[25];
            rB0 = pB0[25];
            rA1 = pA0[59];
            rA2 = pA0[93];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[127];
            rA4 = pA0[161];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[195];
            rA6 = pA0[229];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[263];
            rA8 = pA0[297];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[331];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[26];
            rB0 = pB0[26];
            rA1 = pA0[60];
            rA2 = pA0[94];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[128];
            rA4 = pA0[162];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[196];
            rA6 = pA0[230];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[264];
            rA8 = pA0[298];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[332];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[27];
            rB0 = pB0[27];
            rA1 = pA0[61];
            rA2 = pA0[95];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[129];
            rA4 = pA0[163];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[197];
            rA6 = pA0[231];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[265];
            rA8 = pA0[299];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[333];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[28];
            rB0 = pB0[28];
            rA1 = pA0[62];
            rA2 = pA0[96];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[130];
            rA4 = pA0[164];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[198];
            rA6 = pA0[232];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[266];
            rA8 = pA0[300];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[334];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[29];
            rB0 = pB0[29];
            rA1 = pA0[63];
            rA2 = pA0[97];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[131];
            rA4 = pA0[165];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[199];
            rA6 = pA0[233];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[267];
            rA8 = pA0[301];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[335];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[30];
            rB0 = pB0[30];
            rA1 = pA0[64];
            rA2 = pA0[98];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[132];
            rA4 = pA0[166];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[200];
            rA6 = pA0[234];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[268];
            rA8 = pA0[302];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[336];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[31];
            rB0 = pB0[31];
            rA1 = pA0[65];
            rA2 = pA0[99];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[133];
            rA4 = pA0[167];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[201];
            rA6 = pA0[235];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[269];
            rA8 = pA0[303];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[337];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[32];
            rB0 = pB0[32];
            rA1 = pA0[66];
            rA2 = pA0[100];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[134];
            rA4 = pA0[168];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[202];
            rA6 = pA0[236];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[270];
            rA8 = pA0[304];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[338];
            rC9_0 += m4;
            m4 = rA4 * rB0;
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rA0 = pA0[33];
            rB0 = pB0[33];
            rA1 = pA0[67];
            rA2 = pA0[101];
            rC5_0 += m0;
            m0 = rA0 * rB0;
            rA3 = pA0[135];
            rA4 = pA0[169];
            rC6_0 += m1;
            m1 = rA1 * rB0;
            rA5 = pA0[203];
            rA6 = pA0[237];
            rC7_0 += m2;
            m2 = rA2 * rB0;
            rA7 = pA0[271];
            rA8 = pA0[305];
            rC8_0 += m3;
            m3 = rA3 * rB0;
            rA9 = pA0[339];
            rC9_0 += m4;
            m4 = rA4 * rB0;
/*
 *          Drain pipe on last iteration of K-loop
 */
            rC0_0 += m0;
            m0 = rA5 * rB0;
            rC1_0 += m1;
            m1 = rA6 * rB0;
            rC2_0 += m2;
            m2 = rA7 * rB0;
            rC3_0 += m3;
            m3 = rA8 * rB0;
            rC4_0 += m4;
            m4 = rA9 * rB0;
            rC5_0 += m0;
            rC6_0 += m1;
            rC7_0 += m2;
            rC8_0 += m3;
            rC9_0 += m4;
            pA0 += incAk;
            pB0 += incBk;
            *pC0 = rC0_0;
            pC0[2] = rC1_0;
            pC0[4] = rC2_0;
            pC0[6] = rC3_0;
            pC0[8] = rC4_0;
            pC0[10] = rC5_0;
            pC0[12] = rC6_0;
            pC0[14] = rC7_0;
            pC0[16] = rC8_0;
            pC0[18] = rC9_0;
            pC0 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=M-Mb)
      ATL_zJIK0x0x34TN1x1x34_a1_bX(k, N, 34, alpha, ca + (((Mb) << 5)+((Mb) << 1)), lda, cb, ldb, beta, cc + (((Mb) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
