#!/bin/bash               
#SBATCH -J test               # job name
#SBATCH -o test.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 4              # total number of mpi tasks requested
#SBATCH -p development  # queue (partition) -- normal, development, etc.
#SBATCH -t  00:10:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH -A TG-DMR140116

ibrun /work/03192/priyaj/vasp/vasp.5.3_ncl/vasp          
